spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/pretask;DATABASE_TO_UPPER=FALSE
    username: username
    password: password
    hikari:
      pool-name: SpringBootHikariCP-pool
      maximum-pool-size: 10
      minimum-idle: 10
      max-lifetime: 2000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      idle-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: create-drop
  data:
    web:
      pageable:
        one-indexed-parameters: true
  cache:
    type: redis
    redis:
      cache-null-values: true
      host: localhost
      port: 6379

app:
  kakao:
    api:
      domain: https://dapi.kakao.com/v2/search/blog
      api-key: {api-key}
  naver:
    api:
      domain: https://openapi.naver.com/v1/search/blog.json
      client-id: {client-id}
      client-secret: {client-secret}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true