version: "3"

services:
  redis:
    image: redis:latest
    container_name: search-redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ~/data:/var/lib/redis/data
      - ~/redis/search/redis.conf:/var/lib/redis/redis.conf
